# baremetal settings
step_introspect: true
network_isolation_type: multiple-nics
network_isolation: true

# template copies
baremetal_nic_configs: "{{ local_working_dir }}/openstack-virtual-baremetal/network-templates/nic-configs"
use_resource_registry_nic_configs: true

# This enables container deployments Pike and after
containerized_overcloud: >-
  {% if release in ['newton', 'ocata'] -%}
  false
  {%- else -%}
  true
  {%- endif -%}
delete_docker_cache: true

extra_args: " --control-flavor baremetal --compute-flavor baremetal "

# This featureset is extremely resource intensive, so we disable telemetry
# in order to reduce the overall memory footprint
# This is not required in newton
telemetry_args: >-
   {% if release not in ['newton', 'ocata'] %}
   -e {{ overcloud_templates_path }}/environments/disable-telemetry.yaml
   {% endif %}

run_tempest: false
tempest_config: false
test_ping: true
enable_pacemaker: true
